// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID      string `json:"id"`
	Street  string `json:"street"`
	City    string `json:"city"`
	State   string `json:"state"`
	PinCode string `json:"pinCode"`
}

type Employee struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Age     int      `json:"age"`
	Salary  float64  `json:"salary"`
	Address *Address `json:"address"`
}

type NewEmployee struct {
	Name    string  `json:"name"`
	Age     int     `json:"age"`
	Salary  float64 `json:"salary"`
	Street  string  `json:"street"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	PinCode string  `json:"pinCode"`
}
